url: https://metacell.github.io
baseurl: /OSB_homepage

# Site settings
title: Open Source Brain
email: info@metacell.org
description: ''
githubLink: https://github.com/OpenSourceBrain/OSB_homepage
copyright: 2023 OSB
metacellLink: https://metacell.us/

# Collections
collections:
  - communities
  - elements

# Build settings
markdown: kramdown
permalink: pretty
